# Generated by Django 3.2.4 on 2021-06-04 15:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('month_choice', models.CharField(
                    choices=[('JAN', 'January'), ('FEB', 'February'),
                             ('MAR', 'March'),
                             ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'),
                             ('JULY', 'July'), ('AUG', 'August'),
                             ('SEP', 'September'),
                             ('OCT', 'October'), ('NOV', 'November'),
                             ('DEC', 'December')], max_length=100)),
                ('year_choice', models.CharField(
                    choices=[('2021', '2021'), ('2022', '2022'),
                             ('2023', '2023'),
                             ('2024', '2024'), ('2025', '2025'),
                             ('2026', '2026'),
                             ('2027', '2027')], default='2021',
                    max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('expense', models.BooleanField()),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
